# Generated by Django 5.2.5 on 2025-09-01 20:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip_tracking", "0002_requestlog_city_requestlog_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPThreatSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threat_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=50,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "ip_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ip_tracking.ipaddress",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuspiciousIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("reason", models.TextField()),
                ("flagged_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name="IPWhitelist",
        ),
    ]
